# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 15:08
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('pycolos', '0002_auto_20171231_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
