# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pycolos', '0003_auto_20171231_1608'),
        ('pycolos', '0003_auto_20171231_1552'),
    ]

    operations = [
    ]
