# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 12:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pycolos', '0004_merge_20171231_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='questions_list',
            field=models.CharField(default='', max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
