# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycolos', '0005_testsession_questions_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
    ]
