# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pycolos', '0006_testsession_current_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForbiddenWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ForbiddenWord',
                'verbose_name_plural': 'ForbiddenWords',
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={'verbose_name': 'TestSession', 'verbose_name_plural': 'TestSessions'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'UserAnswer', 'verbose_name_plural': 'UserAnswers'},
        ),
        migrations.AddField(
            model_name='forbiddenword',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pycolos.Question'),
        ),
    ]
