# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycolos', '0007_auto_20180103_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='additional_tests',
            field=models.TextField(blank=True, default=''),
        ),
    ]
